/** Run before every publish. Validates integrity, route isolation and deployment boundaries. */
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import vm from 'node:vm';import {fileURLToPath}from'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');const scripts=s=>[...s.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)].filter(m=>!/\bsrc\s*=/.test(m[1])).map(m=>m[2]);const externalScripts=s=>[...s.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)].filter(m=>/\bsrc\s*=/.test(m[1])).map(m=>{const src=m[1].match(/\bsrc\s*=\s*(?:"([^"]+)"|'([^']+)'|([^\s>]+))/i);assert(src,'Malformed external script URL');assert.equal(m[2].trim(),'','External script must have no inline body');return src[1]||src[2]||src[3]});const sha=s=>crypto.createHash('sha256').update(s).digest('hex');let n=0;function test(name,f){f();n++;console.log('PASS '+name)}
const courses=JSON.parse(read('courses.json'));const config=JSON.parse(read('wrangler.jsonc'));const manifest=JSON.parse(read('public/site-manifest.json'));const headers=read('public/_headers');const home=read('public/index.html');
test('fixed custom domain, no API/backend or database',()=>{assert.equal(config.routes.length,1);assert.equal(config.routes[0].pattern,'learning.jiadi.ai');assert.equal(config.routes[0].custom_domain,true);assert.equal(config.assets.directory,'./public');assert.equal(config.assets.not_found_handling,'404-page');assert.equal(config.main,undefined);assert.equal(config.workers_dev,false);assert.equal(config.preview_urls,false)});
test('generated manifest and catalog agree',()=>{assert.equal(manifest.id,'jiadi-learning-lab');assert.equal(manifest.courseCount,courses.length);assert.equal(manifest.domain,'learning.jiadi.ai');assert.equal((home.match(/<article class="course /g)||[]).length,courses.length)});
test('no unresolved template variables',()=>assert(!/\{\{[A-Z_]+\}\}/.test(home)));
test('CSP permits same-origin worker and requests, with only authored inline hashes',()=>{assert(headers.includes("connect-src 'self'"));assert(headers.includes("worker-src 'self'"));assert(headers.includes("frame-ancestors 'none'"));const policy=headers.match(/script-src([^;]+)/)[1].trim();assert(!policy.includes('unsafe-inline'));assert(!policy.includes('http:'));assert(!policy.includes('https:'));const expected=[...new Set([...scripts(home),...courses.flatMap(c=>scripts(read(`content/courses/${c.slug}/index.html`)))].map(s=>`'sha256-${crypto.createHash('sha256').update(s).digest('base64')}'`))];assert.deepEqual(new Set(policy.split(/\s+/)),new Set(["'self'",...expected]));for(const directive of ['connect-src','worker-src'])assert.equal(headers.match(new RegExp(`${directive} ([^;]+)`))[1].trim(),"'self'")});
test('only approved generated external scripts load from same-origin files',()=>{const allowed=new Set(['/assets/portal/home.js','/assets/portal/pwa.js','/assets/portal/resume.js']);for(const [page,s] of [['home',home],...courses.map(c=>[c.slug,read(`public/courses/${c.slug}/index.html`)])]){const urls=externalScripts(s);assert.deepEqual(new Set(urls.map(u=>u.split('?')[0])),page==='home'?new Set(['/assets/portal/home.js','/assets/portal/pwa.js']):new Set(['/assets/portal/resume.js','/assets/portal/pwa.js']));assert.equal(urls.length,2);for(const url of urls){const parsed=new URL(url,'https://learning.jiadi.ai');assert.equal(parsed.origin,'https://learning.jiadi.ai');assert(allowed.has(parsed.pathname));assert(/^\?v=[0-9a-f]{16}$/.test(parsed.search));assert(fs.existsSync(path.join(root,'public',parsed.pathname.slice(1))))}}});
for(const c of courses){const original=read(`content/courses/${c.slug}/index.html`);const published=read(`public/courses/${c.slug}/index.html`);
 test(c.slug+': original JavaScript byte-identical',()=>assert.deepEqual(scripts(published),scripts(original)));
 test(c.slug+': download is the unchanged, self-contained source',()=>assert.equal(read(`public/downloads/${c.slug}.html`),original));
 test(c.slug+': notes are unchanged',()=>assert.equal(read(`public/courses/${c.slug}/study-notes.md`),read(`content/courses/${c.slug}/study-notes.md`)));
 test(c.slug+': chapters and DOM IDs retained',()=>{const ids=s=>[...s.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.deepEqual(ids(original),ids(published));if(c.format==='dc-fieldguide'){
   const context={window:{}};vm.createContext(context);
   for(const name of ['data.js','content.js','reading.js']){const marker='<script data-course-module="'+name+'">';assert(original.includes(marker));vm.runInContext(original.split(marker)[1].split('</script>')[0],context);}
   const {DC_DATA:D,DC_CONTENT:C,DC_READING:R}=context.window;
   assert.equal(R.length,c.chapters);assert.equal(C.glossary.length,c.terms);assert.equal(R.reduce((n,ch)=>n+ch.sections.length,0),27);
   for(const ch of R)for(const s of ch.sections)for(const id of s.sources)assert(D.sections[id],'Missing source '+id);
   const provenance=JSON.parse(read('content/courses/'+c.slug+'/import-manifest.json'));
   assert.equal(provenance.scripts.length,scripts(original).length);
   for(const asset of provenance.scripts){const marker='<script data-course-module="'+asset.name+'">';assert.equal(sha(original.split(marker)[1].split('</script>')[0]),asset.sha256);}
   for(const asset of provenance.styles){const marker='<style data-course-style="'+asset.name+'">';assert.equal(sha(original.split(marker)[1].split('</style>')[0]),asset.sha256);}
   const reports=[...original.matchAll(/href="data:text\/markdown;charset=utf-8;base64,([^"]+)"/g)];assert.equal(reports.length,2);
   for(const match of reports)assert.equal(sha(Buffer.from(match[1],'base64')),provenance.reportSha256);
 }else{assert.equal(c.format,undefined);assert.equal((original.match(/<section class="lesson(?: active)?"/g)||[]).length,c.chapters)}});
 test(c.slug+': original storage namespace retained',()=>{if(c.storage===null){assert.equal(c.format,'dc-fieldguide');assert(!scripts(original).some(s=>/\b(?:localStorage|sessionStorage)\b/.test(s)));}else{assert(original.includes(c.storage)&&published.includes(c.storage))}});
 test(c.slug+': home link and canonical target',()=>{assert(published.includes('href="../../index.html#courses"'));assert(published.includes(`https://learning.jiadi.ai/courses/${c.slug}/`))});
 test(c.slug+': declared hashes match files',()=>{const m=manifest.courses.find(x=>x.slug===c.slug);assert.equal(sha(original),m.sourceSha256);assert.equal(sha(published),m.publishedSha256)});
 test(c.slug+': all inline scripts parse',()=>scripts(published).forEach(s=>new vm.Script(s)));
}
test('course storage namespaces do not collide',()=>{const keys=courses.map(c=>c.storage).filter(x=>x!==null);for(const a of keys)for(const b of keys)if(a!==b)assert(!a.startsWith(b));assert.equal(new Set(keys).size,keys.length)});
test('standalone courses need no external assets',()=>{for(const c of courses){const s=read('content/courses/'+c.slug+'/index.html');assert(!/<script\b[^>]*\bsrc\s*=/i.test(s));assert(!/<link\b[^>]*rel="stylesheet"/i.test(s));}});
test('homepage inline scripts parse',()=>scripts(home).forEach(s=>new vm.Script(s)));
const files=[];function walk(dir){for(const d of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,d.name);if(d.isDirectory())walk(p);else files.push(p)}}walk(path.join(root,'public'));
test('published directory contains no deployment code, secrets or archives',()=>{for(const p of files){assert(!/\.(zip|key|pem|env|ps1|mjs)$/i.test(p));assert(!/\/\.git/.test(p));assert(fs.statSync(p).size<25*1024*1024)}});
test('no external runtime scripts, stylesheets, trackers or API requests',()=>{for(const p of files.filter(p=>p.endsWith('.html'))){const s=fs.readFileSync(p,'utf8');assert(!/<script\b[^>]*src\s*=\s*["']https?:/i.test(s));assert(!/<link\b[^>]*href\s*=\s*["']https?:[^>]*rel\s*=\s*["']stylesheet/i.test(s));assert(!scripts(s).some(x=>/\bfetch\s*\(|XMLHttpRequest|sendBeacon\s*\(|new\s+WebSocket/.test(x)))}});
test('home/download/notes/preview links resolve inside public',()=>{for(const m of home.matchAll(/(?:href|src)="([^"#]+)"/g)){const href=m[1];if(/^(https?:|data:|mailto:)/.test(href))continue;const plain=href.split('#')[0].split('?')[0];assert(fs.existsSync(path.join(root,'public',plain)),href)}});
test('cover shelf lists every course, newest first',()=>{const slugs=[...home.matchAll(/<li class="shelf-item" data-slug="([^"]+)"/g)].map(m=>m[1]);assert.equal(slugs.length,courses.length);assert.deepEqual(slugs,[...courses].map(c=>c.slug).reverse())});
test('cover detail templates carry the same copy as the grid cards',()=>{const esc=s=>String(s).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));for(const c of courses){const cover=home.match(new RegExp(`<li class="shelf-item" data-slug="${c.slug}"[\\s\\S]*?<template class="cover-detail">([\\s\\S]*?)</template>`));assert.ok(cover,c.slug+' cover template');const detail=cover[1];const cardOpen=home.match(new RegExp(`<article class="course [^>]*data-slug="${c.slug}"[\\s\\S]*?</article>`));assert.ok(cardOpen,c.slug+' grid card');const card=cardOpen[0];for(const fragment of [`href="/courses/${c.slug}/index.html"`,`href="/courses/${c.slug}/study-notes.md"`,`href="/downloads/${c.slug}.html"`]){assert(detail.includes(fragment),c.slug+' detail link '+fragment);assert(card.includes(fragment),c.slug+' grid link '+fragment)}assert(detail.includes(esc(c.description)),c.slug+' description');assert(card.includes(esc(c.description)),c.slug+' grid description');assert(detail.includes(esc(c.firstTask)),c.slug+' first task');assert(card.includes(esc(c.firstTask)),c.slug+' grid first task')}});
test('initial no-JS detail panel is the newest course',()=>{const newest=courses[courses.length-1];const panelStart=home.indexOf('class="shelf-detail');const panelEnd=home.indexOf('<div class="catalog-tools"',panelStart);const panel=home.slice(panelStart,panelEnd);assert(panel.includes(`href="/courses/${newest.slug}/index.html"`));for(const c of courses)if(c.slug!==newest.slug)assert(!panel.includes(`data-slug="${c.slug}"`))});
test('shelf controls stay hidden until JavaScript runs',()=>{assert(/<div class="shelf-nav" hidden>/.test(home));assert(/<div class="shelf-dots"[^>]*\shidden/.test(home));assert(/<p class="shelf-count"[^>]*\shidden/.test(home))});
test('portal storage keys stay limited to favorites, recent and theme',()=>{const js=read('content/portal/home.js');const total=(js.match(/localStorage\./g)||[]).length;const viaHelpers=(js.match(/localStorage\.(?:getItem|setItem)\((?:key|THEME)[,)]/g)||[]).length;assert.equal(total,viaHelpers);assert(js.includes("FAVORITES = 'jiadi-learning-portal:favorites:v1'"));assert(js.includes("RECENT = 'jiadi-learning-portal:recent:v1'"));assert(js.includes("THEME = 'jiadi-learning-portal:theme:v1'"))});
test('cover categories have CSS color variants',()=>{const css=read('public/assets/portal/home.css');for(const cat of new Set(courses.map(c=>c.category)))if(!css.includes(`[data-category="${cat}"]`))console.log('WARN no cover color for category '+cat)});
console.log(`\n${n} static integrity checks passed. Browser/runtime and live hosting need separate tests.`);
